/**
 * Billing Profiles
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwisscomBillingprofilesJavascriptSdk) {
      root.SwisscomBillingprofilesJavascriptSdk = {};
    }
    root.SwisscomBillingprofilesJavascriptSdk.BillingProfileEligibility = factory(root.SwisscomBillingprofilesJavascriptSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BillingProfileEligibility model module.
   * @module model/BillingProfileEligibility
   * @version 1.0.21
   */

  /**
   * Constructs a new <code>BillingProfileEligibility</code>.
   * @alias module:model/BillingProfileEligibility
   * @class
   * @param eligible {Boolean} True or False value to represent the eligibility of billing profile.
   */
  var exports = function(eligible) {
    var _this = this;

    _this['eligible'] = eligible;


  };

  /**
   * Constructs a <code>BillingProfileEligibility</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BillingProfileEligibility} obj Optional instance to populate.
   * @return {module:model/BillingProfileEligibility} The populated <code>BillingProfileEligibility</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('eligible')) {
        obj['eligible'] = ApiClient.convertToType(data['eligible'], 'Boolean');
      }
      if (data.hasOwnProperty('reasonCode')) {
        obj['reasonCode'] = ApiClient.convertToType(data['reasonCode'], 'String');
      }
      if (data.hasOwnProperty('reasonText')) {
        obj['reasonText'] = ApiClient.convertToType(data['reasonText'], 'String');
      }
    }
    return obj;
  }

  /**
   * True or False value to represent the eligibility of billing profile.
   * @member {Boolean} eligible
   */
  exports.prototype['eligible'] = undefined;
  /**
   * The code value to represent the reason why eligibility failed.
   * @member {String} reasonCode
   */
  exports.prototype['reasonCode'] = undefined;
  /**
   * The text describing why the eligibility failed.
   * @member {String} reasonText
   */
  exports.prototype['reasonText'] = undefined;



  return exports;
}));


