/**
 * Billing Profiles
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BillingProfilesCollectionInnerLinks'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BillingProfilesCollectionInnerLinks'));
  } else {
    // Browser globals (root is window)
    if (!root.BillingprofilesJavascriptSdk) {
      root.BillingprofilesJavascriptSdk = {};
    }
    root.BillingprofilesJavascriptSdk.BillingProfileDetails = factory(root.BillingprofilesJavascriptSdk.ApiClient, root.BillingprofilesJavascriptSdk.BillingProfilesCollectionInnerLinks);
  }
}(this, function(ApiClient, BillingProfilesCollectionInnerLinks) {
  'use strict';




  /**
   * The BillingProfileDetails model module.
   * @module model/BillingProfileDetails
   * @version 1.0.14
   */

  /**
   * Constructs a new <code>BillingProfileDetails</code>.
   * @alias module:model/BillingProfileDetails
   * @class
   * @param id {String} The unique identifier of the billing profile
   * @param type {String} The type of the billing profile (e.g.: mobile, ip, wireline).
   * @param links {Array.<module:model/BillingProfilesCollectionInnerLinks>} 
   * @param addresses {Array.<String>} 
   */
  var exports = function(id, type, links, addresses) {
    var _this = this;

    _this['id'] = id;
    _this['type'] = type;

    _this['links'] = links;
    _this['addresses'] = addresses;
  };

  /**
   * Constructs a <code>BillingProfileDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BillingProfileDetails} obj Optional instance to populate.
   * @return {module:model/BillingProfileDetails} The populated <code>BillingProfileDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('language')) {
        obj['language'] = ApiClient.convertToType(data['language'], 'String');
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = ApiClient.convertToType(data['links'], [BillingProfilesCollectionInnerLinks]);
      }
      if (data.hasOwnProperty('addresses')) {
        obj['addresses'] = ApiClient.convertToType(data['addresses'], ['String']);
      }
    }
    return obj;
  }

  /**
   * The unique identifier of the billing profile
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The type of the billing profile (e.g.: mobile, ip, wireline).
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * The preferred language for the billing profile customer.
   * @member {module:model/BillingProfileDetails.LanguageEnum} language
   */
  exports.prototype['language'] = undefined;
  /**
   * @member {Array.<module:model/BillingProfilesCollectionInnerLinks>} links
   */
  exports.prototype['links'] = undefined;
  /**
   * @member {Array.<String>} addresses
   */
  exports.prototype['addresses'] = undefined;


  /**
   * Allowed values for the <code>language</code> property.
   * @enum {String}
   * @readonly
   */
  exports.LanguageEnum = {
    /**
     * value: "en"
     * @const
     */
    "en": "en",
    /**
     * value: "de"
     * @const
     */
    "de": "de",
    /**
     * value: "fr"
     * @const
     */
    "fr": "fr",
    /**
     * value: "it"
     * @const
     */
    "it": "it"  };


  return exports;
}));


