/**
 * Billing Profiles
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SwisscomBillingprofilesJavascriptSdk) {
      root.SwisscomBillingprofilesJavascriptSdk = {};
    }
    root.SwisscomBillingprofilesJavascriptSdk.CustomerAddressInner = factory(root.SwisscomBillingprofilesJavascriptSdk.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CustomerAddressInner model module.
   * @module model/CustomerAddressInner
   * @version 1.0.21
   */

  /**
   * Constructs a new <code>CustomerAddressInner</code>.
   * @alias module:model/CustomerAddressInner
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>CustomerAddressInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomerAddressInner} obj Optional instance to populate.
   * @return {module:model/CustomerAddressInner} The populated <code>CustomerAddressInner</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('houseName')) {
        obj['houseName'] = ApiClient.convertToType(data['houseName'], 'String');
      }
      if (data.hasOwnProperty('street')) {
        obj['street'] = ApiClient.convertToType(data['street'], 'String');
      }
      if (data.hasOwnProperty('houseNumber')) {
        obj['houseNumber'] = ApiClient.convertToType(data['houseNumber'], 'String');
      }
      if (data.hasOwnProperty('postBox')) {
        obj['postBox'] = ApiClient.convertToType(data['postBox'], 'String');
      }
      if (data.hasOwnProperty('zip')) {
        obj['zip'] = ApiClient.convertToType(data['zip'], 'String');
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = ApiClient.convertToType(data['city'], 'String');
      }
    }
    return obj;
  }

  /**
   * The address type of the billing profile. It will either be a street address or a PO Box. A street address consists of either a houseName or a street and houseNumber. A PO Box address always defines a postBox. All addresses may contain a zip code and city.
   * @member {module:model/CustomerAddressInner.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * The name of the house.
   * @member {String} houseName
   */
  exports.prototype['houseName'] = undefined;
  /**
   * The name of the street.
   * @member {String} street
   */
  exports.prototype['street'] = undefined;
  /**
   * The house or street number.
   * @member {String} houseNumber
   */
  exports.prototype['houseNumber'] = undefined;
  /**
   * The post office box number. If there is an empty value then the customer has a postBox but no number is indicated.
   * @member {String} postBox
   */
  exports.prototype['postBox'] = undefined;
  /**
   * The Postal Code.
   * @member {String} zip
   */
  exports.prototype['zip'] = undefined;
  /**
   * The name of the city.
   * @member {String} city
   */
  exports.prototype['city'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "main"
     * @const
     */
    "main": "main",
    /**
     * value: "bill"
     * @const
     */
    "bill": "bill",
    /**
     * value: "correspondence"
     * @const
     */
    "correspondence": "correspondence",
    /**
     * value: "envelope"
     * @const
     */
    "envelope": "envelope"  };


  return exports;
}));


