/**
 * Billing Profiles
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BillingprofilesJavascriptSdk);
  }
}(this, function(expect, BillingprofilesJavascriptSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BillingprofilesJavascriptSdk.BillingProfilesCollectionInnerAddresses();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BillingProfilesCollectionInnerAddresses', function() {
    it('should create an instance of BillingProfilesCollectionInnerAddresses', function() {
      // uncomment below and update the code to test BillingProfilesCollectionInnerAddresses
      //var instane = new BillingprofilesJavascriptSdk.BillingProfilesCollectionInnerAddresses();
      //expect(instance).to.be.a(BillingprofilesJavascriptSdk.BillingProfilesCollectionInnerAddresses);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new BillingprofilesJavascriptSdk.BillingProfilesCollectionInnerAddresses();
      //expect(instance).to.be();
    });

    it('should have the property houseName (base name: "houseName")', function() {
      // uncomment below and update the code to test the property houseName
      //var instane = new BillingprofilesJavascriptSdk.BillingProfilesCollectionInnerAddresses();
      //expect(instance).to.be();
    });

    it('should have the property street (base name: "street")', function() {
      // uncomment below and update the code to test the property street
      //var instane = new BillingprofilesJavascriptSdk.BillingProfilesCollectionInnerAddresses();
      //expect(instance).to.be();
    });

    it('should have the property houseNumber (base name: "houseNumber")', function() {
      // uncomment below and update the code to test the property houseNumber
      //var instane = new BillingprofilesJavascriptSdk.BillingProfilesCollectionInnerAddresses();
      //expect(instance).to.be();
    });

    it('should have the property postBox (base name: "postBox")', function() {
      // uncomment below and update the code to test the property postBox
      //var instane = new BillingprofilesJavascriptSdk.BillingProfilesCollectionInnerAddresses();
      //expect(instance).to.be();
    });

    it('should have the property zip (base name: "zip")', function() {
      // uncomment below and update the code to test the property zip
      //var instane = new BillingprofilesJavascriptSdk.BillingProfilesCollectionInnerAddresses();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new BillingprofilesJavascriptSdk.BillingProfilesCollectionInnerAddresses();
      //expect(instance).to.be();
    });

  });

}));
