/**
 * Billing Profiles
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BillingProfileDetails', 'model/BillingProfileEligibility', 'model/BillingProfilesCollection', 'model/BillingProfilesCollectionInner', 'model/BillingProfilesCollectionInnerLinks', 'model/CustomerAddress', 'model/CustomerAddressInner', 'model/Error', 'api/DefaultApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/BillingProfileDetails'), require('./model/BillingProfileEligibility'), require('./model/BillingProfilesCollection'), require('./model/BillingProfilesCollectionInner'), require('./model/BillingProfilesCollectionInnerLinks'), require('./model/CustomerAddress'), require('./model/CustomerAddressInner'), require('./model/Error'), require('./api/DefaultApi'));
  }
}(function(ApiClient, BillingProfileDetails, BillingProfileEligibility, BillingProfilesCollection, BillingProfilesCollectionInner, BillingProfilesCollectionInnerLinks, CustomerAddress, CustomerAddressInner, Error, DefaultApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var SwisscomBillingprofilesJavascriptSdk = require('index'); // See note below*.
   * var xxxSvc = new SwisscomBillingprofilesJavascriptSdk.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new SwisscomBillingprofilesJavascriptSdk.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new SwisscomBillingprofilesJavascriptSdk.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new SwisscomBillingprofilesJavascriptSdk.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.21
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The BillingProfileDetails model constructor.
     * @property {module:model/BillingProfileDetails}
     */
    BillingProfileDetails: BillingProfileDetails,
    /**
     * The BillingProfileEligibility model constructor.
     * @property {module:model/BillingProfileEligibility}
     */
    BillingProfileEligibility: BillingProfileEligibility,
    /**
     * The BillingProfilesCollection model constructor.
     * @property {module:model/BillingProfilesCollection}
     */
    BillingProfilesCollection: BillingProfilesCollection,
    /**
     * The BillingProfilesCollectionInner model constructor.
     * @property {module:model/BillingProfilesCollectionInner}
     */
    BillingProfilesCollectionInner: BillingProfilesCollectionInner,
    /**
     * The BillingProfilesCollectionInnerLinks model constructor.
     * @property {module:model/BillingProfilesCollectionInnerLinks}
     */
    BillingProfilesCollectionInnerLinks: BillingProfilesCollectionInnerLinks,
    /**
     * The CustomerAddress model constructor.
     * @property {module:model/CustomerAddress}
     */
    CustomerAddress: CustomerAddress,
    /**
     * The CustomerAddressInner model constructor.
     * @property {module:model/CustomerAddressInner}
     */
    CustomerAddressInner: CustomerAddressInner,
    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error: Error,
    /**
     * The DefaultApi service constructor.
     * @property {module:api/DefaultApi}
     */
    DefaultApi: DefaultApi
  };

  return exports;
}));
